language: python
python: 2.7
env:
  matrix:
  - TARGET=test ROBOT_DESIRED_CAPABILITIES="platform:OS X 10.8,browserName:iPhone,version:6,tunnel-identifier:$TRAVIS_JOB_ID"
  - TARGET=test ROBOT_DESIRED_CAPABILITIES="platform:Linux,version:4,browserName:android,tunnel-identifier:$TRAVIS_JOB_ID"
  - TARGET=python-validation.sh ROBOT_BROWSER=firefox ROBOT_DESIRED_CAPABILITIES=tunnel-identifier:$TRAVIS_JOB_ID
  global:
  - secure: |-
        KJVaD49mpVIRWP3UyX6wog9IMXfgCvevPpACrrj0QORKqzZTgCutiMcObjcC
        YAzhLqLUZz3xbc3yi1QDVXn53nzcEpJJOwTE7c5jj1Pj182zfQCvLdKYrhMt
        NBbcFd0qVi3avmuwZa8UpruVtvV8k5D/BP9XL+YU2aC4sZTcYtU=
  - secure: |-
        GpCWOUZHAtNzwfy2ZnMoGZdp2WPHdtsAwdA3/Tg7YPq2jznVrP0XO7Yqw41B
        N7wupruCcwoczcNaFdkTdXEAmOC0QURuydj1OeCXHlR7Ex03DhnjQzgrbiX0
        tuNZzemadyN2mgyl9iMobOLKaY64QYV9RE0PitRySjEHvRRlsw8=
  - ROBOT_BUILD_NUMBER=travis-$TRAVIS_BUILD_NUMBER
  - ROBOT_REMOTE_URL=http://$SAUCE_USERNAME:$SAUCE_ACCESS_KEY@ondemand.saucelabs.com:80/wd/hub
before_script:
  - bash -c "while [ ! -f CONNECTED ]; do sleep 2; done"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -N -t 3 -c travis.cfg install download install
  - bin/buildout -N -t 3 -c travis.cfg
  - curl -O http://saucelabs.com/downloads/Sauce-Connect-latest.zip
  - unzip Sauce-Connect-latest.zip
  - java -jar Sauce-Connect.jar $SAUCE_USERNAME $SAUCE_ACCESS_KEY -i $TRAVIS_JOB_ID -f CONNECTED &
  - JAVA_PID=$!
#after_success:
#  - pip install coveralls
#  - coveralls
after_script:
  - kill $JAVA_PID
script: bin/$TARGET
