language: python
python: 2.7
env:
  - TARGET=test
  - TARGET=python-validation.sh
#  - TARGET=coverage.sh
  global:
  - secure: |-
      RhbnYEMoKQfm5viGRtFpvljXJr8sjRUet89LBPW3EHaonXTKuxWz0RQ/Py9r
      kHIcJgw4WodAUYGc1ITzbiQL9ssy1whgL0VjfWOYjUcyZvATwme8ZQUZ78Wy
      y7PDyPlbv/TcWvn1yUvoUZE/ATkmtJw6x+DkD+I4+QNlUtBYz6g=
  - secure: |-
      LJ6/9dm+2srw3QgFaQq+po9CYODF3zl6P6uBgK8GIcrS1R49k9JTuLgEUnHb
      yAfM0AW9Bwmp5xLJ6VMkw6nEcGPto6BIhBNnDMjquNq0b8gZ7oWniw1uhSVe
      Sfq7NGPqw9I/tWfwoe0PNl/SgTfmkIMWAOcZRvKND5XzXn7OigM=
  - ROBOT_BUILD_NUMBER=travis-$TRAVIS_BUILD_NUMBER
  - ROBOT_REMOTE_URL=http://$SAUCE_USERNAME:$SAUCE_ACCESS_KEY@ondemand.saucelabs.com:80/wd/hub
  - ROBOT_DESIRED_CAPABILITIES=tunnel-identifier:$TRAVIS_JOB_ID
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -N -t 3 -c travis.cfg install download install
  - bin/buildout -N -t 3 -c travis.cfg
  - curl -O http://saucelabs.com/downloads/Sauce-Connect-latest.zip
  - unzip Sauce-Connect-latest.zip
  - java -jar Sauce-Connect.jar $SAUCE_USERNAME $SAUCE_ACCESS_KEY -i $TRAVIS_JOB_ID -f CONNECTED &
  - JAVA_PID=$!
  - bash -c "while [ ! -f CONNECTED ]; do sleep 2; done"
#after_success:
#  - pip install coveralls
#  - coveralls
after_script:
  - kill $JAVA_PID
script: bin/$TARGET
