---
language: python
python: 2.7
#http://selenium.googlecode.com/git/docs/api/py/webdriver/selenium.webdriver.common.desired_capabilities.html
env:
  matrix:
  - TARGET=test ROBOT_SELENIUM_VERSION=" " ROBOT_DESIRED_CAPABILITIES="platform:ANDROID,browserName:android,version:,tunnel-identifier:$TRAVIS_JOB_NUMBER"
  - TARGET=test ROBOT_SELENIUM_VERSION=" " ROBOT_DESIRED_CAPABILITIES="platform:OS X 10.8,browserName:iPhone,version:6,tunnel-identifier:$TRAVIS_JOB_NUMBER"
#  - TARGET=python-validation.sh ROBOT_BROWSER=firefox ROBOT_DESIRED_CAPABILITIES="tunnel-identifier:$TRAVIS_JOB_NUMBER"
#  - TARGET=coverage.sh ROBOT_BROWSER=firefox ROBOT_DESIRED_CAPABILITIES="tunnel-identifier:$TRAVIS_JOB_NUMBER"
#  - TARGET=test ROBOT_DESIRED_CAPABILITIES="platform:OS X 10.8,browserName:iPhone,version:6,tunnel-identifier:$TRAVIS_JOB_NUMBER"
#  - TARGET=test ROBOT_DESIRED_CAPABILITIES="platform:Linux,version:4,browserName:android,tunnel-identifier:$TRAVIS_JOB_NUMBER"
  global:
  - secure: |-
        KJVaD49mpVIRWP3UyX6wog9IMXfgCvevPpACrrj0QORKqzZTgCutiMcObjcC
        YAzhLqLUZz3xbc3yi1QDVXn53nzcEpJJOwTE7c5jj1Pj182zfQCvLdKYrhMt
        NBbcFd0qVi3avmuwZa8UpruVtvV8k5D/BP9XL+YU2aC4sZTcYtU=
  - secure: |-
        GpCWOUZHAtNzwfy2ZnMoGZdp2WPHdtsAwdA3/Tg7YPq2jznVrP0XO7Yqw41B
        N7wupruCcwoczcNaFdkTdXEAmOC0QURuydj1OeCXHlR7Ex03DhnjQzgrbiX0
        tuNZzemadyN2mgyl9iMobOLKaY64QYV9RE0PitRySjEHvRRlsw8=
  - ROBOT_BUILD_NUMBER=travis-$TRAVIS_BUILD_NUMBER
  - ROBOT_REMOTE_URL=http://$SAUCE_USERNAME:$SAUCE_ACCESS_KEY@ondemand.saucelabs.com:80/wd/hub
install:
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -N -t 3 -c travis.cfg -q install download install
  - bin/buildout -N -t 3 -c travis.cfg -q
before_script:
  - curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash
script: bin/$TARGET
after_success:
  - pip install coveralls
  - coveralls
